language: cpp
os:
- linux
- osx
dist: trusty
compiler:
- clang
- gcc
python:
  - "3.4"
matrix:
  exclude:
  - os: osx
    compiler: gcc
sudo: required
branches:
  only:
    - master
before_install:
- chmod +x dist/travis/*.sh
- dist/travis/before_script.sh
script:
- dist/travis/script.sh
