language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: PAPUGA_WITH_PYTHON=YES PAPUGA_WITH_PHP=NO PAPUGA_WITH_LUA=NO
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: PAPUGA_WITH_PYTHON=NO PAPUGA_WITH_PHP=NO PAPUGA_WITH_LUA=YES
    - os: linux
      dist: xenial
      compiler: clang
      env: PAPUGA_WITH_PYTHON=YES PAPUGA_WITH_PHP=NO PAPUGA_WITH_LUA=NO
    - os: linux
      dist: xenial
      compiler: clang
      env: PAPUGA_WITH_PYTHON=NO PAPUGA_WITH_PHP=YES PAPUGA_WITH_LUA=NO
    - os: linux
      dist: xenial
      compiler: clang
      env: PAPUGA_WITH_PYTHON=NO PAPUGA_WITH_PHP=NO PAPUGA_WITH_LUA=YES
    - os: linux
      dist: xenial
      compiler: gcc
      env: PAPUGA_WITH_PYTHON=YES PAPUGA_WITH_PHP=NO PAPUGA_WITH_LUA=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: PAPUGA_WITH_PYTHON=NO PAPUGA_WITH_PHP=YES PAPUGA_WITH_LUA=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: PAPUGA_WITH_PYTHON=NO PAPUGA_WITH_PHP=NO PAPUGA_WITH_LUA=YES

sudo: required
branches:
  only:
    - master
before_install:
- chmod +x dist/travis/*.sh
- dist/travis/before_script.sh
script:
- dist/travis/script.sh
