cmake_minimum_required( VERSION 2.8 FATAL_ERROR )

# --------------------------------------
# PHP 7.x
# --------------------------------------
macro( CHECK_PHP7_EXECUTABLE  _candidate )
if( NOT PHP7_EXECUTABLE )
execute_process( COMMAND  ${_candidate}  ${CMAKE_CURRENT_LIST_DIR}/version.php
			   RESULT_VARIABLE  RET_PHPVERSION 
			   ERROR_VARIABLE  STDERR_PHPVERSION
			   OUTPUT_VARIABLE  STDOUT_PHPVERSION 
	                   ERROR_STRIP_TRAILING_WHITESPACE
			   OUTPUT_STRIP_TRAILING_WHITESPACE )
set( OUT_PHPVERSION "${STDERR_PHPVERSION}${STDOUT_PHPVERSION}" )
if( ${RET_PHPVERSION} STREQUAL "" OR ${RET_PHPVERSION} STREQUAL "0" )
message( STATUS "Call ${_candidate}  ${CMAKE_CURRENT_LIST_DIR}/version.php result: '${OUT_PHPVERSION}' " )
string( SUBSTRING  "${OUT_PHPVERSION}"  0  1  PHPVERSIONSTR )
if( ${PHPVERSIONSTR}  STREQUAL  "7" )
set( PHP7_EXECUTABLE  "${_candidate}" )
string( REGEX REPLACE  "/php([0-9\\.]*)$" "/php-config\\1"  PHP7_CONFIG_EXECUTABLE  ${PHP7_EXECUTABLE} )
string( SUBSTRING  "${OUT_PHPVERSION}"  0  3  PHP7_VERSION )

execute_process( COMMAND  ${PHP7_CONFIG_EXECUTABLE} --version
			   RESULT_VARIABLE  RET_CFG_PHPVERSION
			   ERROR_VARIABLE  STDERR_CFG_PHPVERSION
			   OUTPUT_VARIABLE  STDOUT_CFG_PHPVERSION 
	                   ERROR_STRIP_TRAILING_WHITESPACE
			   OUTPUT_STRIP_TRAILING_WHITESPACE )
set( OUT_CFG_PHPVERSION "${STDERR_CFG_PHPVERSION}${STDOUT_CFG_PHPVERSION}" )
MESSAGE( STATUS "Call '${PHP7_CONFIG_EXECUTABLE} --version'  error '${RET_CFG_PHPVERSION}' result '${OUT_CFG_PHPVERSION}'" )
if( ${RET_CFG_PHPVERSION} STREQUAL "" OR ${RET_CFG_PHPVERSION} STREQUAL "0" )
string( SUBSTRING  "${OUT_CFG_PHPVERSION}"  0  1  PHPCFGVERSIONSTR )
if( NOT ${PHPCFGVERSIONSTR}  STREQUAL  "7" )
unset( PHP7_EXECUTABLE )
unset( PHP7_CONFIG_EXECUTABLE )
unset( PHP7_VERSION )
endif( NOT ${PHPCFGVERSIONSTR}  STREQUAL  "7" )
endif( ${RET_CFG_PHPVERSION} STREQUAL "" OR ${RET_CFG_PHPVERSION} STREQUAL "0" )

else( ${PHPVERSIONSTR}  STREQUAL  "7" )
unset( PHP7_EXECUTABLE )
unset( PHP7_CONFIG_EXECUTABLE )
unset( PHP7_VERSION )
endif( ${PHPVERSIONSTR}  STREQUAL  "7" )
else( ${RET_PHPVERSION} STREQUAL "" OR ${RET_PHPVERSION} STREQUAL "0")
unset( PHP7_EXECUTABLE )
unset( PHP7_CONFIG_EXECUTABLE )
unset( PHP7_VERSION )
endif( ${RET_PHPVERSION} STREQUAL "" OR ${RET_PHPVERSION} STREQUAL "0" )
endif( NOT PHP7_EXECUTABLE )
endmacro( CHECK_PHP7_EXECUTABLE )

macro( ECHO_COMMAND_RESULT )
execute_process( COMMAND  ${ARGN}
			   RESULT_VARIABLE  _rt
			   OUTPUT_VARIABLE  _result
			   OUTPUT_STRIP_TRAILING_WHITESPACE )
if( ${_rt} STREQUAL "" OR ${_rt} STREQUAL "0" )
message( STATUS "Result of '${ARGN}': ${_result}" ) 
else( ${_rt} STREQUAL "" OR ${_rt} STREQUAL "0" )
message( STATUS "Call of '${ARGN}' returned ${_rt}" )
endif( ${_rt} STREQUAL "" OR ${_rt} STREQUAL "0" )
endmacro( ECHO_COMMAND_RESULT )

macro( EXEC_FIND_BY_COMMAND )
if (NOT PHP7_EXECUTABLE)
execute_process( COMMAND  ${ARGN} 
			   RESULT_VARIABLE  RET_PYTHON_PATH
			   OUTPUT_VARIABLE  PYTHON_PROGRAM_PATH
			   OUTPUT_STRIP_TRAILING_WHITESPACE )
if( ${RET_PYTHON_PATH} STREQUAL "" OR ${RET_PYTHON_PATH} STREQUAL "0" )
CHECK_PHP7_EXECUTABLE( ${PYTHON_PROGRAM_PATH} )
if( PHP7_EXECUTABLE )
MESSAGE( STATUS "Found to program path of PHP 7: '${PHP7_EXECUTABLE}' " )
endif( PHP7_EXECUTABLE )
endif( ${RET_PYTHON_PATH} STREQUAL "" OR ${RET_PYTHON_PATH} STREQUAL "0" )
endif (NOT PHP7_EXECUTABLE)
endmacro( EXEC_FIND_BY_COMMAND )

macro( EXEC_FIND_PROGRAM  _prgname )
if (NOT PHP7_EXECUTABLE)
set( FINDPATH $ENV{PATH} )
string( REPLACE ":"  ";"  FINDPATH  ${FINDPATH} )
separate_arguments( FINDPATH )
foreach( FP  ${FINDPATH} )
CHECK_PHP7_EXECUTABLE( "${FP}/${_prgname}" )
endforeach( FP  ${FINDPATH} )
find_program( PHPCANDIDATE NAME "${_prgname}" HINTS  ${FINDPATH} )
if( PHPCANDIDATE AND NOT PHPCANDIDATE STREQUAL "PHPCANDIDATE-NOTFOUND" )
CHECK_PHP7_EXECUTABLE( "${PHPCANDIDATE}" )
endif( PHPCANDIDATE AND NOT PHPCANDIDATE STREQUAL "PHPCANDIDATE-NOTFOUND" )
endif (NOT PHP7_EXECUTABLE)
endmacro( EXEC_FIND_PROGRAM  _prgname )

foreach( PHPVERSION "7.9" "7.8" "7.7" "7.6" "7.5" "7.4" "7.3" "7.2" "7.1" "7.0" "7" "" )
EXEC_FIND_PROGRAM( "php${PHPVERSION}" )
EXEC_FIND_BY_COMMAND( "which" "php${PHPVERSION}" )
endforeach( PHPVERSION "7.9" "7.8" "7.7" "7.6" "7.5" "7.4" "7.3" "7.2" "7.1" "7.0" "7" "" )

if( PHP7_EXECUTABLE )
MESSAGE( STATUS "PHP 7.x executable: ${PHP7_EXECUTABLE}" )
MESSAGE( STATUS "PHP 7.x config executable:  ${PHP7_CONFIG_EXECUTABLE}" )

execute_process( COMMAND  ${PHP7_CONFIG_EXECUTABLE} --includes
			   RESULT_VARIABLE  RET_CFG
			   OUTPUT_VARIABLE  PHP7_INCLUDES )
if( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
string( REPLACE "-I"  ""  PHP7_INCLUDE_DIRS  ${PHP7_INCLUDES}  )
string( STRIP  ${PHP7_INCLUDE_DIRS}  PHP7_INCLUDE_DIRS )
string( REPLACE " "  ";"  PHP7_INCLUDE_DIRS  ${PHP7_INCLUDE_DIRS}  )
MESSAGE( STATUS "PHP 7.x include dirs: ${PHP7_INCLUDE_DIRS}" )
else( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
message( STATUS "Call '${PHP7_CONFIG_EXECUTABLE} --includes' returns '${RET_CFG}' " )
set( PHP7_INCLUDE_DIRS "" )
endif( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )

execute_process( COMMAND  ${PHP7_CONFIG_EXECUTABLE} --ldflags 
			   RESULT_VARIABLE  RET_CFG
			   OUTPUT_VARIABLE PHP7_LDFLAGS )
if( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
string( REGEX MATCHALL "-L[^ ]*" PHP7_LDFLAGS  "${PHP7_LDFLAGS}" )
string( REPLACE "-L"  " "  PHP7_LIBRARY_DIRS  "${PHP7_LDFLAGS}"  )
string( STRIP  "${PHP7_LIBRARY_DIRS}"  PHP7_LIBRARY_DIRS )
separate_arguments( PHP7_LIBRARY_DIRS)
MESSAGE( STATUS "PHP 7.x library dirs: ${PHP7_LIBRARY_DIRS}" )
else( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
message( WARNING "Call '${PHP7_CONFIG_EXECUTABLE} --ldflags' returns '${RET_CFG}' " )
set( PHP7_LIBRARY_DIRS "" )
endif( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )

execute_process( COMMAND  ${PHP7_CONFIG_EXECUTABLE} --libs RESULT_VARIABLE  RET_CFG  OUTPUT_VARIABLE PHP7_LIBS )
if( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
string( REGEX MATCHALL "-l[^ ]*" PHP7_LIBS  "${PHP7_LIBS}" )
string( REPLACE "-l"  " "  PHP7_LIBRARIES  ${PHP7_LIBS}  )
string( STRIP  ${PHP7_LIBRARIES}  PHP7_LIBRARIES )
separate_arguments( PHP7_LIBRARIES)
MESSAGE( STATUS "PHP 7.x libraries: ${PHP7_LIBRARIES}" )
else( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
message( WARNING "Call '${PHP7_CONFIG_EXECUTABLE} --libs' returns '${RET_CFG}' " )
set( PHP7_LIBS "" )
endif( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )

execute_process( COMMAND  ${PHP7_CONFIG_EXECUTABLE} --extension-dir  RESULT_VARIABLE  RET_CFG  OUTPUT_VARIABLE  PHP7_EXTENSION_DIR )
if( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
string( STRIP  "${PHP7_EXTENSION_DIR}"  PHP7_EXTENSION_DIR )
MESSAGE( STATUS "PHP 7.x extension dir: ${PHP7_EXTENSION_DIR}" )
else( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
message( WARNING "Call '${PHP7_CONFIG_EXECUTABLE} --extension-dir' returns '${RET_CFG}' " )
set( PHP7_EXTENSION_DIR  "PHP7_EXTENSION_DIR-NOTFOUND" )
endif( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )

execute_process( COMMAND  ${PHP7_EXECUTABLE}  ${CMAKE_CURRENT_LIST_DIR}/getPhpIniFile.php
			  RESULT_VARIABLE  RET_CFG
			  OUTPUT_VARIABLE  PHP7_INI_FILE )
if( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
string( STRIP  "${PHP7_INI_FILE}"  PHP7_INI_FILE )
MESSAGE( STATUS "PHP 7.x  .ini file: ${PHP7_INI_FILE}" )
else( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )
message( WARNING "Call '${PHP7_EXECUTABLE} ${CMAKE_CURRENT_LIST_DIR}/getPhpIniFile.php' returns '${RET_CFG}' " )
set( PHP7_INI_FILE  "PHP7_INI_FILE-NOTFOUND" )
endif( ${RET_CFG} STREQUAL "" OR ${RET_CFG} STREQUAL "0" )

MESSAGE( STATUS "PHP 7.x  version: ${PHP7_VERSION}" )

else( PHP7_EXECUTABLE )
MESSAGE( FATAL_ERROR "Unable to relocate PHP 7.x interpreter" )
endif( PHP7_EXECUTABLE )
